version: "3.8"
services: 
  mongo:
    image: mongo
    ports: 
      - "3030:27017"
    volumes: 
      - mongo-data:/data/db
  web-service:
    image: mongo-express
    ports: 
      - "8081:8081"
    environment: 
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    depends_on: 
      - mongo
volumes: 
  mongo-data:
    driver: local