version: "3"
services: 
  api-server:
    image: blog-server
    ports: 
      - "5000:5000"
    networks: 
      - mern-app
    depends_on: 
      - database
  database:
    image: mongo
    ports: 
      - "27017:27017"
    networks: 
      - mern-app
    volumes: 
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge 
volumes: 
  mongo-data:
    driver: local